image: php:7.4

pipelines:
  default:
    - step:
        name: Build and deploy to InfinityFree
        script:
          - apt-get update && apt-get install -y lftp
          - php -r "file_exists('.env') || copy('.env.example', '.env');"
          - php artisan key:generate
          - composer install --no-interaction --prefer-dist --optimize-autoloader
          - npm install && npm run production
          # Upload files to InfinityFree via FTP
          - lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -R public/ /htdocs"
