image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: 'Deployment'
        script:
          - echo 'Deploying to production'
          # Install Composer
          - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          - php -r "unlink('composer-setup.php');"
          # Run Composer install
          - composer install --no-dev --prefer-dist
          - php artisan optimize
          - php artisan route:cache
          - php artisan view:cache
          - php artisan config:cache
          - php artisan migrate --force
          - npm install && npm run production
          - lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; set ftp:ssl-allow yes; mirror -R ./ /htdocs"
